/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.Date;

/**
 *
 * @author Assunção
 */
public class JanelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form JanelaMenu
     */
    public JanelaMenu() {
        initComponents();
        setTitle("Menu Inicial");
        URL url = this.getClass().getResource("a.png");  
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(iconeTitulo);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janelaMenu = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSistema = new javax.swing.JMenu();
        abrirChamado = new javax.swing.JMenuItem();
        consultarChamadoAberto = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        incluirUsuario = new javax.swing.JMenuItem();
        excluirUsuario = new javax.swing.JMenuItem();
        editarUsuario = new javax.swing.JMenuItem();
        menuGerenciamento = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        incluirCaso = new javax.swing.JMenuItem();
        consultarCasos = new javax.swing.JMenuItem();
        excluirCaso = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        atenderChamado = new javax.swing.JMenuItem();
        consultarChamado = new javax.swing.JMenuItem();
        excluirChamado = new javax.swing.JMenuItem();

        javax.swing.GroupLayout janelaMenuLayout = new javax.swing.GroupLayout(janelaMenu.getContentPane());
        janelaMenu.getContentPane().setLayout(janelaMenuLayout);
        janelaMenuLayout.setHorizontalGroup(
            janelaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        janelaMenuLayout.setVerticalGroup(
            janelaMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuSistema.setText("Sistema");

        abrirChamado.setText("Abrir Chamado");
        abrirChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirChamadoActionPerformed(evt);
            }
        });
        menuSistema.add(abrirChamado);

        consultarChamadoAberto.setText("Consultar Chamado(s) Aberto(s)");
        consultarChamadoAberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarChamadoAbertoActionPerformed(evt);
            }
        });
        menuSistema.add(consultarChamadoAberto);

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        menuSistema.add(sair);

        jMenuBar1.add(menuSistema);

        menuUsuario.setText("Usuário");

        incluirUsuario.setText("Incluir Usuário");
        incluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(incluirUsuario);

        excluirUsuario.setText("Excluir Usuário");
        excluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(excluirUsuario);

        editarUsuario.setText("Editar Usuário");
        editarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(editarUsuario);

        jMenuBar1.add(menuUsuario);

        menuGerenciamento.setText("Gerenciamento");

        jMenu1.setText("Casos");

        incluirCaso.setText("Incluir Caso");
        incluirCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirCasoActionPerformed(evt);
            }
        });
        jMenu1.add(incluirCaso);

        consultarCasos.setText("Consultar Casos");
        consultarCasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarCasosActionPerformed(evt);
            }
        });
        jMenu1.add(consultarCasos);

        excluirCaso.setText("Excluir Caso");
        excluirCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCasoActionPerformed(evt);
            }
        });
        jMenu1.add(excluirCaso);

        menuGerenciamento.add(jMenu1);

        jMenu2.setText("Chamados");

        atenderChamado.setText("Atender Chamado");
        atenderChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderChamadoActionPerformed(evt);
            }
        });
        jMenu2.add(atenderChamado);

        consultarChamado.setText("Consultar Chamados");
        consultarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarChamadoActionPerformed(evt);
            }
        });
        jMenu2.add(consultarChamado);

        excluirChamado.setText("Excluir Chamado");
        excluirChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirChamadoActionPerformed(evt);
            }
        });
        jMenu2.add(excluirChamado);

        menuGerenciamento.add(jMenu2);

        jMenuBar1.add(menuGerenciamento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incluirCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirCasoActionPerformed
        JanelaIncluirCaso janela = new JanelaIncluirCaso();
        janela.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_incluirCasoActionPerformed

    private void abrirChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirChamadoActionPerformed
        this.dispose();
        JanelaAbrirChamado janela = new JanelaAbrirChamado();
        janela.setVisible(true);
    }//GEN-LAST:event_abrirChamadoActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);        
    }//GEN-LAST:event_sairActionPerformed

    private void incluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirUsuarioActionPerformed
        this.dispose();
        JanelaCadastrarUsuario janela = new JanelaCadastrarUsuario();
        janela.setVisible(true);
    }//GEN-LAST:event_incluirUsuarioActionPerformed

    private void excluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirUsuarioActionPerformed
       
    }//GEN-LAST:event_excluirUsuarioActionPerformed

    private void excluirCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCasoActionPerformed
        
        JanelaListaCasos janela = new JanelaListaCasos();
        janela.setVisible(true);        
        this.setVisible(false);
    }//GEN-LAST:event_excluirCasoActionPerformed

    private void atenderChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderChamadoActionPerformed
        this.dispose();
        JanelaListaChamados janela = new JanelaListaChamados();        
        janela.setVisible(true);
    }//GEN-LAST:event_atenderChamadoActionPerformed

    private void consultarChamadoAbertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarChamadoAbertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarChamadoAbertoActionPerformed

    private void excluirChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirChamadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirChamadoActionPerformed

    private void editarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarUsuarioActionPerformed

    private void consultarCasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarCasosActionPerformed
        JanelaListaCasos janela = new JanelaListaCasos();
        this.dispose();
        janela.setVisible(true);
    }//GEN-LAST:event_consultarCasosActionPerformed

    private void consultarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarChamadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarChamadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirChamado;
    private javax.swing.JMenuItem atenderChamado;
    private javax.swing.JMenuItem consultarCasos;
    private javax.swing.JMenuItem consultarChamado;
    private javax.swing.JMenuItem consultarChamadoAberto;
    private javax.swing.JMenuItem editarUsuario;
    private javax.swing.JMenuItem excluirCaso;
    private javax.swing.JMenuItem excluirChamado;
    private javax.swing.JMenuItem excluirUsuario;
    private javax.swing.JMenuItem incluirCaso;
    private javax.swing.JMenuItem incluirUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JFrame janelaMenu;
    private javax.swing.JMenu menuGerenciamento;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenuItem sair;
    // End of variables declaration//GEN-END:variables
}
