/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bd.ConnectorHelpDesk;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author Assunção
 */
public class JanelaListaChamados extends javax.swing.JFrame {

    /**
     * Creates new form JanelaListaChamados
     */
    public JanelaListaChamados() {
        initComponents();
        setTitle("Lista de Chamados");
        URL url = this.getClass().getResource("a.png");  
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("glpi?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        chamadoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Chamado c");
        chamadoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : chamadoQuery.getResultList();
        entityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("glpi?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        chamadoQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT c FROM Chamado c");
        chamadoList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : chamadoQuery1.getResultList();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaListaChamados = new javax.swing.JTable();
        botaoSair = new javax.swing.JButton();
        botaoAtenderChamado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, chamadoList1, tabelaListaChamados);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idChamado}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tituloChamado}"));
        columnBinding.setColumnName("Título");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricaoChamado}"));
        columnBinding.setColumnName("Descrição");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tabelaListaChamados);
        tabelaListaChamados.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelaListaChamados.getColumnModel().getColumn(1).setPreferredWidth(250);
        tabelaListaChamados.getColumnModel().getColumn(2).setPreferredWidth(255);

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoAtenderChamado.setText("Atender Chamado");
        botaoAtenderChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtenderChamadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoAtenderChamado)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSair)
                    .addComponent(botaoAtenderChamado))
                .addGap(21, 21, 21))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        this.dispose();
        JanelaMenu janela = new JanelaMenu();
        janela.setVisible(true);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoAtenderChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtenderChamadoActionPerformed
        this.dispose();
        
        
        JanelaAtenderChamado janela = new JanelaAtenderChamado();
        
        Integer id = (Integer) tabelaListaChamados.getValueAt(tabelaListaChamados.getSelectedRow(), 0);
        String titulo = (String) tabelaListaChamados.getValueAt(tabelaListaChamados.getSelectedRow(), 1);
        String descricao = (String) tabelaListaChamados.getValueAt(tabelaListaChamados.getSelectedRow(), 2);        
        JanelaAtenderChamado.setChamado(new ConnectorHelpDesk().retrieveRequest(id));
        janela.preencherJanela(id,titulo,descricao,JanelaAtenderChamado.getChamado().getDataChamado());
        janela.setVisible(true);
    }//GEN-LAST:event_botaoAtenderChamadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaListaChamados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaListaChamados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaListaChamados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaListaChamados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaListaChamados().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtenderChamado;
    private javax.swing.JButton botaoSair;
    private java.util.List<gui.Chamado> chamadoList;
    private java.util.List<gui.Chamado> chamadoList1;
    private javax.persistence.Query chamadoQuery;
    private javax.persistence.Query chamadoQuery1;
    private javax.persistence.EntityManager entityManager;
    private javax.persistence.EntityManager entityManager0;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaListaChamados;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
