/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import entidades.Caso;
import entidades.Chamado;
import entidades.Descricaocaso;
import entidades.Solucaocaso;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import jcolibri.cbrcore.CBRQuery;
import jcolibri.method.retrieve.RetrievalResult;
import rbc.CBRAplication;
/**
 *
 * @author Assunção
 */
public class JanelaAtenderChamado extends javax.swing.JFrame {

    /**
     * Creates new form JanelaAtenderChamado
     */
    
    public static Chamado chamado;

    public static Chamado getChamado() {
        return chamado;
    }

    public static void setChamado(Chamado chamado) {
        JanelaAtenderChamado.chamado = chamado;
        
    }
    
    public JanelaAtenderChamado() {        
        initComponents();
        setTitle("Atender Chamado");
        URL url = this.getClass().getResource("a.png");  
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(iconeTitulo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoChamado = new javax.swing.JTextArea();
        botaoBuscarCasosSemelhantes = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        idChamado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tituloChamado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoData = new javax.swing.JTextField();
        botaoSolucionarChamado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID:");

        jLabel2.setText("Descrição do Problema:");

        descricaoChamado.setBackground(new java.awt.Color(240, 240, 240));
        descricaoChamado.setColumns(20);
        descricaoChamado.setRows(5);
        jScrollPane1.setViewportView(descricaoChamado);

        botaoBuscarCasosSemelhantes.setText("Buscar Casos Semelhantes");
        botaoBuscarCasosSemelhantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarCasosSemelhantesActionPerformed(evt);
            }
        });

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        idChamado.setEditable(false);

        jLabel3.setText("Título:");

        tituloChamado.setBackground(new java.awt.Color(240, 240, 240));

        jLabel4.setText("Data:");

        campoData.setEditable(false);

        botaoSolucionarChamado.setText("Solucionar Chamado");
        botaoSolucionarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSolucionarChamadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloChamado)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoSair)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(botaoSolucionarChamado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoBuscarCasosSemelhantes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tituloChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoBuscarCasosSemelhantes)
                    .addComponent(botaoSolucionarChamado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(botaoSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoBuscarCasosSemelhantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarCasosSemelhantesActionPerformed
        
        
        try{
            //ArrayList<RetrievalResult> listaSimilares = new ArrayList<RetrievalResult>();
            CBRAplication aplication = new CBRAplication();
            
            aplication.configure();
            
            aplication.preCycle();
            
            CBRQuery consulta = new CBRQuery();
            
            Descricaocaso descricaoCaso = new Descricaocaso();            
            descricaoCaso.setDescricao(descricaoChamado.getText());
            descricaoCaso.setTitulo(tituloChamado.getText());
            descricaoCaso.preencherCampos();
            
            consulta.setDescription(descricaoCaso);
            
            aplication.cycle(consulta);
            
            
            
            //listaSimilares= aplication.getResultado();
            
            JanelaCasosSemelhantes janela = new JanelaCasosSemelhantes();            
            
            ArrayList<RetrievalResult> lista = new ArrayList<RetrievalResult>();
            
            for(RetrievalResult res: aplication.getResultado()){
                
                lista.add(res);
                
                
                
                
                
                
                
            }
            
            janela.listaResultado=lista;
            janela.PreencherJanela();
            janela.idChamado= chamado.getIdChamado();
            this.dispose();
            janela.setVisible(true);
            
        }catch(Exception e){
            System.out.println("-->"+e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_botaoBuscarCasosSemelhantesActionPerformed

    private void botaoSolucionarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSolucionarChamadoActionPerformed
        JanelaIncluirCaso janela = new JanelaIncluirCaso(tituloChamado.getText(),descricaoChamado.getText(),chamado.getIdChamado());
        this.dispose();
        janela.setVisible(true);
    }//GEN-LAST:event_botaoSolucionarChamadoActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        this.dispose();
        JanelaMenu janela =new JanelaMenu();
        janela.show();
                
    }//GEN-LAST:event_botaoSairActionPerformed

    public void preencherJanela(Integer id, String titulo, String descricao, String data){
        idChamado.setText(""+id);
        tituloChamado.setText(titulo);
        descricaoChamado.setText(descricao);
        campoData.setText(data);
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaAtenderChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaAtenderChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaAtenderChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaAtenderChamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaAtenderChamado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoBuscarCasosSemelhantes;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoSolucionarChamado;
    private javax.swing.JTextField campoData;
    private javax.swing.JTextArea descricaoChamado;
    private javax.swing.JTextField idChamado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tituloChamado;
    // End of variables declaration//GEN-END:variables
}
