/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bd.ConnectorHelpDesk;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import jcolibri.cbrcore.CBRCase;
import entidades.Caso;

/**
 *
 * @author Assunção
 */
public class JanelaListaCasos extends javax.swing.JFrame {

    /**
     * Creates new form JanelaListaCasos
     */
    public JanelaListaCasos() {
        initComponents();
        setTitle("Base de Casos");
        qtdCasos.setText("" + tabelaListaCasos.getRowCount());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("glpi?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        casoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Caso c");
        casoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : casoQuery.getResultList();
        entityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("glpi?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        casoQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT c FROM Caso c");
        casoList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : casoQuery1.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaListaCasos = new javax.swing.JTable();
        botaoSair = new javax.swing.JButton();
        incluirCaso = new javax.swing.JButton();
        excluirCaso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        qtdCasos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, casoList1, tabelaListaCasos);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idCaso}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idDescricao}"));
        columnBinding.setColumnName("Titulo");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idDescricao}"));
        columnBinding.setColumnName("Descricao");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idSolucao}"));
        columnBinding.setColumnName("Solucao");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, casoList, org.jdesktop.beansbinding.ObjectProperty.create(), tabelaListaCasos, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        tabelaListaCasos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaListaCasosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tabelaListaCasosMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaListaCasosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaListaCasos);
        tabelaListaCasos.getColumnModel().getColumn(0).setMinWidth(50);
        tabelaListaCasos.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelaListaCasos.getColumnModel().getColumn(0).setMaxWidth(50);
        tabelaListaCasos.getColumnModel().getColumn(1).setMinWidth(258);
        tabelaListaCasos.getColumnModel().getColumn(1).setPreferredWidth(258);
        tabelaListaCasos.getColumnModel().getColumn(1).setMaxWidth(258);
        tabelaListaCasos.getColumnModel().getColumn(2).setMinWidth(516);
        tabelaListaCasos.getColumnModel().getColumn(2).setPreferredWidth(516);
        tabelaListaCasos.getColumnModel().getColumn(2).setMaxWidth(516);

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        incluirCaso.setText("Incluir Caso");
        incluirCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirCasoActionPerformed(evt);
            }
        });

        excluirCaso.setText("Excluir Caso");
        excluirCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirCasoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Quantidade de Casos:");

        qtdCasos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1340, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtdCasos)
                        .addGap(0, 1200, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoSair)
                        .addGap(489, 489, 489)
                        .addComponent(excluirCaso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(incluirCaso)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(qtdCasos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSair)
                    .addComponent(excluirCaso)
                    .addComponent(incluirCaso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaListaCasosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaListaCasosMousePressed
    }//GEN-LAST:event_tabelaListaCasosMousePressed

    private void tabelaListaCasosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaListaCasosMouseClicked
        if (evt.getClickCount() > 1) {

            System.out.println(tabelaListaCasos.getValueAt(tabelaListaCasos.getSelectedRow(), 0));
        }

    }//GEN-LAST:event_tabelaListaCasosMouseClicked

    private void tabelaListaCasosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaListaCasosMouseEntered
    }//GEN-LAST:event_tabelaListaCasosMouseEntered

    private void incluirCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirCasoActionPerformed
        this.dispose();
        JanelaIncluirCaso janela = new JanelaIncluirCaso();
        
        janela.setVisible(true);

        
    }//GEN-LAST:event_incluirCasoActionPerformed

    private void excluirCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirCasoActionPerformed


        int id = Integer.parseInt("" + tabelaListaCasos.getValueAt(tabelaListaCasos.getSelectedRow(), 0));


        try {
            ArrayList<CBRCase> lista = new ArrayList<CBRCase>();
            Caso caso = new Caso();

            caso.setIdCaso(id);            

            if (caso.getIdCaso().equals(null)) {
                JOptionPane.showMessageDialog(null, "Favor Selecionar um Caso!");
            } else {
                ConnectorHelpDesk conect = new ConnectorHelpDesk();
                lista.add(caso);
                
                conect.deleteCases(lista);         
                
                
                
                
                
            }




        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Caso Não Incluído na Base de Casos\n" + e.getMessage());

        }

    }//GEN-LAST:event_excluirCasoActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        this.dispose();
        JanelaMenu janela = new JanelaMenu();
        janela.setVisible(true);
    }//GEN-LAST:event_botaoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaListaCasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaListaCasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaListaCasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaListaCasos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaListaCasos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSair;
    private java.util.List<gui.Caso> casoList;
    private java.util.List<gui.Caso> casoList1;
    private javax.persistence.Query casoQuery;
    private javax.persistence.Query casoQuery1;
    private javax.persistence.EntityManager entityManager;
    private javax.persistence.EntityManager entityManager0;
    private javax.swing.JButton excluirCaso;
    private javax.swing.JButton incluirCaso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel qtdCasos;
    private javax.swing.JTable tabelaListaCasos;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
