/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bd.ConnectorHelpDesk;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import entidades.Caso;
import entidades.Descricaocaso;
import entidades.Solucaocaso;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import jcolibri.cbrcore.CBRCase;
import jcolibri.method.retrieve.RetrievalResult;

/**
 *
 * @author Assunção
 */
public class JanelaCasosSemelhantes extends javax.swing.JFrame {

    /**
     * Creates new form JanelaAtenderChamado
     */
    public ArrayList<RetrievalResult> listaResultado;
    public int idlista = 0;
    public int idChamado;
    public JanelaCasosSemelhantes() {
        initComponents();
        setTitle("Casos Semelhantes");
        URL url = this.getClass().getResource("a.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);


    }

    public void PreencherJanela() {
        this.campoId.setText("" + listaResultado.get(idlista).get_case().getID());
        DecimalFormat df = new DecimalFormat("0.##");
        Double similaridade = (listaResultado.get(idlista).getEval() * 100);
        String valor = df.format(similaridade);
        this.campoSimilaridade.setText(valor + "%");
        Caso c = (Caso) listaResultado.get(idlista).get_case();
        this.campoTitulo.setText(c.getDescricaocaso().getTitulo());
        //this.campoTitulo.setText(""+listaResultado.get(idlista).get_case().getClass().);
        this.campoDescricao.setText("" + listaResultado.get(idlista).get_case().getDescription());
        this.campoSolucao.setText("" + listaResultado.get(idlista).get_case().getSolution());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoSolucao = new javax.swing.JTextArea();
        botaoSair = new javax.swing.JButton();
        campoId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoTitulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoDescricao = new javax.swing.JTextArea();
        botaoUtilizarSolucao = new javax.swing.JButton();
        botaoAdaptarSolucao = new javax.swing.JButton();
        botaoProximo = new javax.swing.JButton();
        botaoAnterior = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        campoSimilaridade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID:");

        jLabel2.setText("Descrição do Problema:");

        campoSolucao.setEditable(false);
        campoSolucao.setBackground(new java.awt.Color(240, 240, 240));
        campoSolucao.setColumns(20);
        campoSolucao.setLineWrap(true);
        campoSolucao.setRows(5);
        jScrollPane1.setViewportView(campoSolucao);

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        campoId.setEditable(false);

        jLabel3.setText("Título:");

        campoTitulo.setEditable(false);

        jLabel6.setText("Solução:");

        campoDescricao.setBackground(new java.awt.Color(240, 240, 240));
        campoDescricao.setColumns(20);
        campoDescricao.setLineWrap(true);
        campoDescricao.setRows(5);
        jScrollPane2.setViewportView(campoDescricao);

        botaoUtilizarSolucao.setText("Utilizar Solução");
        botaoUtilizarSolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUtilizarSolucaoActionPerformed(evt);
            }
        });

        botaoAdaptarSolucao.setText("Adaptar Solução");
        botaoAdaptarSolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdaptarSolucaoActionPerformed(evt);
            }
        });

        botaoProximo.setText("Próximo->");
        botaoProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProximoActionPerformed(evt);
            }
        });

        botaoAnterior.setText("<-Anterior");
        botaoAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAnteriorActionPerformed(evt);
            }
        });

        jLabel4.setText("Similaridade:");

        campoSimilaridade.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoAdaptarSolucao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoUtilizarSolucao))
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addComponent(campoTitulo)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addComponent(botaoSair)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(campoSimilaridade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(botaoAnterior)
                                    .addGap(18, 18, 18)
                                    .addComponent(botaoProximo))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoProximo)
                    .addComponent(botaoAnterior)
                    .addComponent(jLabel4)
                    .addComponent(campoSimilaridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoUtilizarSolucao)
                    .addComponent(botaoAdaptarSolucao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAnteriorActionPerformed
        if (idlista <= 0) {
        } else {
            idlista--;
            this.campoId.setText("" + listaResultado.get(idlista).get_case().getID());
            DecimalFormat df = new DecimalFormat("0.##");
            Double similaridade = (listaResultado.get(idlista).getEval() * 100);
            String valor = df.format(similaridade);
            this.campoSimilaridade.setText(valor + "%");
            Caso c = (Caso) listaResultado.get(idlista).get_case();
            this.campoTitulo.setText(c.getDescricaocaso().getTitulo());
            this.campoDescricao.setText("" + listaResultado.get(idlista).get_case().getDescription());
            this.campoSolucao.setText("" + listaResultado.get(idlista).get_case().getSolution());
        }



    }//GEN-LAST:event_botaoAnteriorActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        this.dispose();
        JanelaListaChamados janela = new JanelaListaChamados();
        janela.setVisible(true);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProximoActionPerformed

        if ((idlista < listaResultado.size() - 1) && idlista >= 0) {

            idlista++;
            this.campoId.setText("" + listaResultado.get(idlista).get_case().getID());
            DecimalFormat df = new DecimalFormat("0.##");
            Double similaridade = (listaResultado.get(idlista).getEval() * 100);
            String valor = df.format(similaridade);
            this.campoSimilaridade.setText(valor + "%");
            Caso c = (Caso) listaResultado.get(idlista).get_case();
            this.campoTitulo.setText(c.getDescricaocaso().getTitulo());
            this.campoDescricao.setText("" + listaResultado.get(idlista).get_case().getDescription());
            this.campoSolucao.setText("" + listaResultado.get(idlista).get_case().getSolution());


        } else {
            JOptionPane.showMessageDialog(null, "Não existe mais Casos Semelhantes");
        }
    }//GEN-LAST:event_botaoProximoActionPerformed

    private void botaoUtilizarSolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUtilizarSolucaoActionPerformed
        try {
            ArrayList<CBRCase> lista = new ArrayList<CBRCase>();
            Caso caso = new Caso();
            Descricaocaso descricaoCaso = new Descricaocaso();
            Solucaocaso solucaoCaso = new Solucaocaso();
            descricaoCaso.setTitulo(JanelaAtenderChamado.getChamado().getTituloChamado());
            descricaoCaso.setDescricao(JanelaAtenderChamado.getChamado().getDescricaoChamado());
            solucaoCaso.setSolucao(campoSolucao.getText());
            caso.setDescricaocaso(descricaoCaso);
            caso.setSolucaocaso(solucaoCaso);
            ConnectorHelpDesk conect = new ConnectorHelpDesk();
            conect.deleteRequest(idChamado);
            //new ConnectorHelpDesk().deleteRequest(idlista);              

            lista.add(caso);
            conect.storeCaseDescription(descricaoCaso);
            conect.storeCaseSolution(solucaoCaso);
            conect.storeCases(lista);
            JOptionPane.showMessageDialog(null, "Chamado Solucionado com Sucesso!");
            this.dispose();
            JanelaListaChamados janela = new JanelaListaChamados();
            janela.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Caso Não Foi Possível Solucionar o Chamado\n" + e.getMessage());
        }

    }//GEN-LAST:event_botaoUtilizarSolucaoActionPerformed

    private void botaoAdaptarSolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdaptarSolucaoActionPerformed
        JanelaAdaptarSolucao janela = new JanelaAdaptarSolucao();
        janela.getCampoTitulo().setText(JanelaAtenderChamado.getChamado().getTituloChamado());
        janela.getCampoDescricao().setText(JanelaAtenderChamado.getChamado().getDescricaoChamado());
        janela.getCampoSolucao().setText(campoSolucao.getText());
        janela.id = this.idlista;
        this.dispose();
        janela.setVisible(true);
    }//GEN-LAST:event_botaoAdaptarSolucaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCasosSemelhantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCasosSemelhantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCasosSemelhantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCasosSemelhantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCasosSemelhantes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdaptarSolucao;
    private javax.swing.JButton botaoAnterior;
    private javax.swing.JButton botaoProximo;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoUtilizarSolucao;
    private javax.swing.JTextArea campoDescricao;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoSimilaridade;
    private javax.swing.JTextArea campoSolucao;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
