package entidades;
// Generated 01/09/2016 22:34:59 by Hibernate Tools 3.2.1.GA

import jcolibri.cbrcore.CBRCase;




/**
 * Caso generated by hbm2java
 */
public class Caso extends CBRCase implements java.io.Serializable {


     private Integer idCaso;
     public Descricaocaso descricaocaso;
     public Solucaocaso solucaocaso;

    public Caso() {
    }

    public Caso(Descricaocaso descricaocaso, Solucaocaso solucaocaso) {
       this.descricaocaso = descricaocaso;
       this.solucaocaso = solucaocaso;
    }
   
    public Integer getIdCaso() {
        return this.idCaso;
    }
    
    public void setIdCaso(Integer idCaso) {
        this.idCaso = idCaso;
    }
    public Descricaocaso getDescricaocaso() {
        return this.descricaocaso;
    }
    
    public void setDescricaocaso(Descricaocaso descricaocaso) {
        this.descricaocaso = descricaocaso;
    }
    public Solucaocaso getSolucaocaso() {
        return this.solucaocaso;
    }
    
    public void setSolucaocaso(Solucaocaso solucaocaso) {
        this.solucaocaso = solucaocaso;
    }




}


