package entidades;
// Generated 01/09/2016 22:34:59 by Hibernate Tools 3.2.1.GA



/**
 * Chamado generated by hbm2java
 */
public class Chamado  implements java.io.Serializable {


     private Integer idChamado;
     private Usuario usuario;
     private String tituloChamado;
     private String descricaoChamado;
     private String dataChamado;
     private boolean chamadoAtendido;

    public Chamado() {
    }

    public Chamado(Usuario usuario, String tituloChamado, String descricaoChamado, String dataChamado, boolean chamadoAtendido) {
       this.usuario = usuario;
       this.tituloChamado = tituloChamado;
       this.descricaoChamado = descricaoChamado;
       this.dataChamado = dataChamado;
       this.chamadoAtendido = chamadoAtendido;
    }
   
    public Integer getIdChamado() {
        return this.idChamado;
    }
    
    public void setIdChamado(Integer idChamado) {
        this.idChamado = idChamado;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTituloChamado() {
        return this.tituloChamado;
    }
    
    public void setTituloChamado(String tituloChamado) {
        this.tituloChamado = tituloChamado;
    }
    public String getDescricaoChamado() {
        return this.descricaoChamado;
    }
    
    public void setDescricaoChamado(String descricaoChamado) {
        this.descricaoChamado = descricaoChamado;
    }
    public String getDataChamado() {
        return this.dataChamado;
    }
    
    public void setDataChamado(String dataChamado) {
        this.dataChamado = dataChamado;
    }
    public boolean isChamadoAtendido() {
        return this.chamadoAtendido;
    }
    
    public void setChamadoAtendido(boolean chamadoAtendido) {
        this.chamadoAtendido = chamadoAtendido;
    }




}


