package entidades;
// Generated 01/09/2016 22:34:59 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import jcolibri.cbrcore.Attribute;
import jcolibri.cbrcore.CaseComponent;
import jcolibri.extensions.textual.IE.opennlp.IETextOpenNLP;

/**
 * Descricaocaso generated by hbm2java
 */
public class Descricaocaso implements java.io.Serializable, CaseComponent {

    private Integer idDescricaoCaso;
    public String idDescricao;
    private String titulo;
    private String descricao;
    private Set casos = new HashSet(0);
    public IETextOpenNLP descricaoCaso;
    public IETextOpenNLP tituloCaso;

    public Descricaocaso() {
    }

    public Descricaocaso(String titulo, String descricao) {
        this.titulo = titulo;
        this.descricao = descricao;
    }

    public Descricaocaso(String titulo, String descricao, Set casos) {
        this.titulo = titulo;
        this.descricao = descricao;
        this.casos = casos;
    }

    public void preencherCampos() {
        this.descricaoCaso = new IETextOpenNLP(descricao);
        this.tituloCaso = new IETextOpenNLP(titulo);
        this.idDescricao = ""+idDescricaoCaso;
    }

    public Integer getIdDescricaoCaso() {
        return this.idDescricaoCaso;
    }

    public void setIdDescricaoCaso(Integer idDescricaoCaso) {
        this.idDescricaoCaso = idDescricaoCaso;
    }

    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Set getCasos() {
        return this.casos;
    }

    public void setCasos(Set casos) {
        this.casos = casos;
    }

    @Override
    public Attribute getIdAttribute() {
        return new Attribute("idDescricao", this.getClass());
    }
    @Override
    public String toString(){
        return descricao;
    }
}
