package entidades;
// Generated 01/09/2016 22:34:59 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import jcolibri.cbrcore.Attribute;
import jcolibri.cbrcore.CaseComponent;

/**
 * Solucaocaso generated by hbm2java
 */
public class Solucaocaso  implements java.io.Serializable, CaseComponent {


     private Integer idSolucaoCaso;
     private String solucao;
     private Set casos = new HashSet(0);

    public Solucaocaso() {
    }

	
    public Solucaocaso(String solucao) {
        this.solucao = solucao;
    }
    public Solucaocaso(String solucao, Set casos) {
       this.solucao = solucao;
       this.casos = casos;
    }
   
    public Integer getIdSolucaoCaso() {
        return this.idSolucaoCaso;
    }
    
    public void setIdSolucaoCaso(Integer idSolucaoCaso) {
        this.idSolucaoCaso = idSolucaoCaso;
    }
    public String getSolucao() {
        return this.solucao;
    }
    
    public void setSolucao(String solucao) {
        this.solucao = solucao;
    }
    public Set getCasos() {
        return this.casos;
    }
    
    public void setCasos(Set casos) {
        this.casos = casos;
    }

    @Override
    public Attribute getIdAttribute() {
        return new Attribute("solucao", this.getClass());
    }

    public String toString(){
        return solucao;
    }



}


