package entidades;
// Generated 01/09/2016 22:34:59 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String matricula;
     private String nome;
     private String senha;
     private boolean admin;
     private Set chamados = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String matricula, String nome, String senha, boolean admin) {
        this.matricula = matricula;
        this.nome = nome;
        this.senha = senha;
        this.admin = admin;
    }
    public Usuario(String matricula, String nome, String senha, boolean admin, Set chamados) {
       this.matricula = matricula;
       this.nome = nome;
       this.senha = senha;
       this.admin = admin;
       this.chamados = chamados;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public boolean isAdmin() {
        return this.admin;
    }
    
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }
    public Set getChamados() {
        return this.chamados;
    }
    
    public void setChamados(Set chamados) {
        this.chamados = chamados;
    }




}


